### ISSUE TITLE
Compare IAUX BookReader wrapper with Dweb BookReader wrapper

### ISSUE THREAD

**Issue by iisa** [internetarchive/iaux#260]
**Task Details**
- DWeb BookReader wrapper makes a call to `BookReaderJSIA` endpoint for manifest while the IAUX BookReader takes the manifest as a prop.

What can we do to consolidate to 1 React wrapped BookReader?

> What needs to be done and why?

Just an overall audit, which may lead to more questions before defining spec & implementation.

**Comment by iisa** [comment]
@mitra42 this is the ticket to investigate how we can consolidate BookReader components.

**Comment by mitra42** [comment]
I'm not sure if you are WFH or PTO, so I'll update this thread as I learn more …

Just taking a look …, I'm seeing several things that you could be referring to as the IAUX wrapper. 

`sandbox/threatres/bookreader-theatre` which calls ia-js-client and passes the data to a BookReaderJSIA component.  I'm presuming this isn't the wrapper you mean since AFAIK nothing in ia-js-client really works (I'm not using it for anything, and don't believe @jbuckner is). 

Then we have … 

`sandbox/bookreader-component/bookreader-wrapper-main`  goes straight to new Book-reader
`sandbox/bookreader-component/bookreader-jsia.js` passes manifest (I presume) to BookReaderJSIAinit

Then I have `DwebBookReaderWrapper` which fetches data and calls BookReaderJSIAinit

Note that `bookreader/BookReaderJSIAinit` calls new BookReader after adding lending info etc
 
I’m unsure which of these you’d like to merge DwebBookReaderWrapper with - both of the IAUX alternatives seem incomplete - specifically `bookreader-jsia.js` doesn't do any setup of its options, while `bookreader-theatre` doesnt handle the lending info. 

I don't see a problem integrating with either of them, I'd retain DwebBookReaderWrapper, but just do the fetch, and then wrap whichever of your components we are using. 

Except  ... that if integrated with `bookreader-theatre` then the functionality of JSIAinit has to be incorporated, and if integrated with `bookreader-jsia` then the options need to be setup before calling it ... 

@iisa Can you clarify which you are using and whether I'm right about what is missing from each.

**Comment by mitra42** [comment]
@jbuckner  - do you know which of these components @iisa is using?

**Comment by mitra42** [comment]
@iisa -  could you take a look at the above ...

**Comment by iisa** [comment]
sorry for the delay, `sandbox/bookreader-component/bookreader-wrapper-main` is the only component in play right now.

**Comment by mitra42** [comment]
Thanks they look basically the same but ... 
I have a call 
```
        item.fetch_bookreader({page: this.props.page}, (err, ai) => {      // Load Bookreader data async
            const rawAPI = RawBookReaderResponse.fromArchiveItem(item);
            BookReaderJSIAinit(rawAPI.cooked(), options); // Note don't need to change during cooking as will be delivered by server (or cooked in mirror) as appropriate
        });
```
which fetches all the book data (the JSIA call) and then creates the book using BookReaderJSIA
while bookreader-wrapper-main just goes straight to `new BookReader`

I'm not sure what to do here, there is quite a bit of functionality in BookReaderJSIA including `extendBookReaderPrototype` which is fairly complex, so I don't have a lot of confidence in duplicating that JSIA code in my wrapper in a way that tracks changes. 

Any thoughts or am I missing something ?

**Comment by mitra42** [comment]
Closing this as they are now integrated into a single wrapper `ia-components/sandbox/bookreader-component/bookreader-wrapper-main.jsx` which is included by both Dweb and the new media player (for liner notes).
