### ISSUE TITLE
Front Page: Proper Grid Display of Top Collections at the Archive

### ISSUE THREAD

**Issue by MonilBhavsar** [internetarchive/iaux#36]
**Description**

> What problem are we solving? What does the experience look like today? What are the symptoms? Please describe the component/story/add on related to the issue.

The Top Collections at the Archive  have grids which are having different heights of the elements.

**Evidence / Screenshot (if possible)**

![FireShot Capture 009 - Internet Archive_ Digital Library of Free   Borrowable Books, Movies,_ - archive org](https://user-images.githubusercontent.com/32012005/55003070-a9775100-4ffd-11e9-8f6b-f4e02d8db000.png)

**Expectation**

The grids can be properly aligned with equal heights. Like the first row of above image.
The square grids can be implemented like the image below with equal heights. According to me it will be a good design idea.

![myiVg](https://user-images.githubusercontent.com/32012005/55003434-6e295200-4ffe-11e9-9a42-986848812d5f.jpg)

**Comment by koderjoker** [comment]
In order to implement a uniform grid system for not only the home page but also for search results, all `searchResultCard`s need to be brought under a uniform system. Some issues we'd have to go over would be:

- Deciding on a common height, width and shape for the [searchResultCard--collection](https://github.com/internetarchive/iaux/wiki/Design-Pattern-Library#searchresultcard--collection), [searchResultCard--media](https://github.com/internetarchive/iaux/wiki/Design-Pattern-Library#searchresultcard--media) and [searchResultCard--account](https://github.com/internetarchive/iaux/wiki/Design-Pattern-Library#searchresultcard--account) components

- Giving all [searchResultCard--media](https://github.com/internetarchive/iaux/wiki/Design-Pattern-Library#searchresultcard--media) image tiles a fixed height and width, and letting the image inside them maintain their original aspect ratio (similar to the search results component at open library where the image resides inside `bookcover`, except that they don't have fixed heights, relevant issue [here](https://github.com/internetarchive/openlibrary/pull/1853))

-  Giving all [searchResultCard--media](https://github.com/internetarchive/iaux/wiki/Design-Pattern-Library#searchresultcard--media) components which don't contain Join Waitlist or Borrow buttons (which cause them to have different shapes) a 'read button' to maintain uniformity.

- Restricting [hidden-list--sin](https://github.com/internetarchive/iaux/wiki/Design-Pattern-Library#hidden-list--sin) and [author-text](https://github.com/internetarchive/iaux/wiki/Design-Pattern-Library#author-text) to contain the same number of lines of text

**Comment by iisa** [comment]
Closing this in favor of using #38 as the main issue.
