### ISSUE TITLE
Request guidance for GSOC 2021

### ISSUE THREAD

**Issue by Swapnil-2001** [internetarchive/iaux#543]
Hello,

My name is Swapnil Sengupta and I'm a second year student of Jadavpur University, Kolkata, India. I would love to work with the Internet Archive on the **Archive.org Front-end Web Components (IAUX)** project as a part of this year's GSOC, as described in the official [Project Ideas page](https://docs.google.com/document/d/1qt1dfk6rNE3yzMJXbriDjpeDrn6LQeiXviREvnXP6bE/edit#). 

There isn't much time left before we need to submit proposals, and I would be very grateful for some assistance on how to get started with the project, or at least fix some relevant bugs. @iisa could you please help?

Thank you

**Comment by kaiwalyakoparkar** [comment]
Same assistance needed.

**Comment by crew-guy** [comment]
Hey Swapnil ! I am Ankit, I wish to apply for the **Bookreader** project with Internet Archive. Since we both seem to be beginners, let's get in touch and help each other grow this codebase and do something meaningful
I'm connecting with you on LinkedIn so that we can share further contact details and interact faster !

**Comment by Swapnil-2001** [comment]
Sure, @crew-guy, sounds great!

**Comment by thomaskuntzz** [comment]
Hi, I’m Thomas, I’m currently studying Computer Science at EPFL and I would also be interested to submit a GSoC 2021 proposal for IAUX, but can’t really find information about how to go about it besides the aforementioned [Google Doc](https://docs.google.com/document/d/1qt1dfk6rNE3yzMJXbriDjpeDrn6LQeiXviREvnXP6bE/edit#). Should I just send an email to info@archive.org?

**Comment by mekarpeles** [comment]
Hi everyone, Mek here from the Internet Archive's https://github.com/internetarchive/openlibrary project. I lead a different team so I may not be the perfect resource, but I'll do my darnedest to make sure everyone is taken care of. Please accept my apology that we didn't somehow connect the dots on this issue. We were under the impression that GSoC requests were being correctly routed to our staff by email and there was supposedly an error which we believe has since been fixed!

I've replied to a few of you over email -- @thomaskuntzz, @crew-guy... Thank you for being persistent and reaching out. @Swapnil-2001 and @kaiwalyakoparkar please expect replies from me shortly (if you've already reached out) or please kindly send me an email to mek@archive.org so I can assist you with next steps.

Thank you again for your patience and excited to offer feedback, answer questions, and review your proposals.

**Comment by crew-guy** [comment]
Thanks a lot Mek !! Glad you came for us 🙏🏻

**Comment by sarthakkundra** [comment]
Hi @mekarpeles I had emailed Mr Mitra Ardron who forwaded my email to you. It'll be great if you can revert to that, it'll be great. I can email you again if that's required :)

**Comment by Krishna-Sivakumar** [comment]
Hello @mekarpeles, I've emailed you too!
